// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ0TQNC1WzGCr6_gn9S6eIBFOOfLjFQGc',
    appId: '1:512321205006:android:86f5c92a7d29719301dd5f',
    messagingSenderId: '512321205006',
    projectId: 'platable-d3e07',
    databaseURL: 'https://platable-d3e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'platable-d3e07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJuEPUMfE3KLUVBDS0LqmyjkM7ssOIuVY',
    appId: '1:512321205006:ios:0fc56d8a9bf84bd301dd5f',
    messagingSenderId: '512321205006',
    projectId: 'platable-d3e07',
    databaseURL: 'https://platable-d3e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'platable-d3e07.appspot.com',
    androidClientId: '512321205006-4v3r4lus7hiqfhiqa46e2tpkst5iuioa.apps.googleusercontent.com',
    iosClientId: '512321205006-c9nd04eu23ismas3amb39sdqvcu0cmq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.platable',
  );
}
